ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell  # See pyproject.toml for args
        additional_dependencies:
          - tomli
        exclude: '^docs/changes\.rst$|^\.?pylintrc$'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.15.21'
    hooks:
      - id: ruff
        args: [--select=I, --fix, --exit-non-zero-on-fix, --show-fixes]
        types: [python]
